In [1]:
import numpy as np

def check_square(matrix):
    return matrix.shape[0] == matrix.shape[1]

def orthogonal(matrix):
    if not check_square(matrix):
        return False
    else:
        transp = np.transpose(matrix)
        id_matrix = np.eye(matrix.shape[0])

        return np.array_equal(np.dot(transp, matrix), id_matrix)
    
def orthonormal(matrix):
    if orthogonal(matrix):
        for i in range(matrix.shape[0]):
            if not sum(matrix[i][j]**2 for j in range(matrix.shape[0]))**0.5 == 1:
                return False
            else:
                return True
    else:
        return False
            

In [2]:
matrix = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

is_ortho = orthogonal(matrix)
is_ortho_norm = orthonormal(matrix)

print(matrix)
print(f"Orthogonal: {is_ortho}, Orthonormal: {is_ortho_norm}")

[[1 0 0]
 [0 1 0]
 [0 0 1]]
Orthogonal: True, Orthonormal: True
